language: java
jdk: oraclejdk13
# sudo: required

addons:
  sonarcloud:
    organization: "mlg-party" # der key der organisation auf sonarcloud.io
    token:
      secure: $SONAR_TOKEN       # $SONAR_TOKEN -> Umgebungsvariable auf travis-ci.org

script:
  - mvn test -B
  # - sonar-scanner

notifications:
  email: 
    on_success: never # default: change
    on_failure: never # default: always
