server:
  port: 8090
spring:
  datasource:
    url: "jdbc:mysql://test.nope-api.systems:3306/nope_check?useSSL=false&allowPublicKeyRetrieval=true"
    username: "assetinspector"
    password: "iI5o0PkOOxCzRPb6NvVY#"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
        ddl-auto: validate
        id:
          new_generator_mappings: false